PROJECT_s2i/PROJECT_s2i/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PROJECT_s2i/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views 
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.sign_up, name='signup'),
]

PROJECT_s2i/content/urls.py
from django.urls import path
from . import views

app_name = "content"

urlpatterns = [
    path('', views.homepage, name='home'), # HOME
    path('info/', views.info, name='info'), # LEARN MORE 
    path('posts/', views.posts, name='posts'), # ELENCO E CREAZIONE POST 
    path('posts_mng/', views.posts_mng, name='posts_mng'), # GESTIONE POST 
    path('post/<int:id>/', views.post_detail, name='post_detail'), # DETTAGLIO POST 
    path('user/<int:id>/', views.user_id, name='user_id'), # USER E CORRISPONDENTE ID
    path('APIs/', views.APIs, name='APIs'), # ELENCO ENDPOINTS API
    path('api/1h/', views.api_posts_1h, name='api_posts_1h'), # ENDPOINT PER 1H 
    path('api/<str:str>/', views.api_posts_str, name='api_posts_str'), # ENDPOINT PER RICERCA DI UNA STRINGA 
]

PROJECT_s2i/content/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from .utils import sendTransaction
import hashlib

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    title = models.CharField(max_length=250)
    on_chain = models.BooleanField(default=True)
    hash = models.CharField(max_length=32, default=None, blank=True, null=True)
    txId = models.CharField(max_length=66, default=None, blank=True, null=True)

    def writeOnChain(self):
        self.hash = hashlib.sha256(self.content.encode('utf-8')).hexdigest()
        self.txId = sendTransaction(self.hash)
        self.save()

    def __str__(self):
        return self.title

PROJECT_s2i/content/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content', 'on_chain',)

    
    # Controllo testo inserito dagli utenti 
    def clean(self):
        content = self.cleaned_data.get('content')
        title = self.cleaned_data.get('title')
        ban = ['hack', 'HACK', 'HaCk', 'hAcK', 'haCK', 'HAck', 'hACk', 'HacK', 'Hack', 'hAck', 'haCk', 'hacK']
        for word in ban:
            if word in content or word in title:
                raise forms.ValidationError("You typed in some banned words!")
        return self.cleaned_data

PROJECT_s2i/content/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import PostForm
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
import redis


# Create your views here.
def homepage(request):
    first_3_posts = Post.objects.filter().order_by('-datetime')[0:3]
    return render(request, 'content/homepage.html', {'posts':first_3_posts})


def info(request):
    return render(request, 'content/info.html', {})

@login_required
def user_id(request, id):
    user_by_id = User.objects.filter(id=id)[0]
    return render(request, 'content/user_id.html', {'user_by_id':user_by_id})


@user_passes_test(lambda u: u.is_superuser)
def posts_mng(request):
    users = User.objects.all()
    posts = Post.objects.all()
    return render(request, 'content/posts_mng.html', {'posts':posts, 'users':users})


@login_required
def posts(request):
    
    # CONTROLLO IP 
    # !----- Necessita SERVER REDIS attivo -----!
    # curr_ip = request.META.get("REMOTE_ADDR")
    # client = redis.StrictRedis(host=#, port=#, db=0) <---- INSERIRE HOST E PORT ----!
    # curr_user = request.user
    # if client.get(f'{curr_user}'):
    #     user_ip = client.get(f'{curr_user}').decode('utf-8')
    #     if curr_ip != user_ip:
    #         print(f"ATTENZIONE! L'ip dell'utente {curr_user} è cambiato da '{user_ip}' a '{curr_ip}'")
    # client.set(f'{curr_user}', f'{curr_ip}'.encode('utf-8'))
    
    posts_list_dt = Post.objects.filter().order_by('-datetime')
    
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.datetime = timezone.now()
            post.save()
            if post.on_chain: 
                post.writeOnChain()
            id=post.id
            return redirect('content:post_detail', id=id)
    else:
        form = PostForm()
    
    return render(request, 'content/posts.html', {'posts':posts_list_dt, 'form': form})


@login_required
def post_detail(request, id):
    posts_by_id = Post.objects.filter(id=id)
    return render(request, 'content/post_detail.html', {'posts': posts_by_id})




@login_required
def APIs(request):
    return render(request, 'content/APIs.html')


def api_posts_1h(request):
    response = []
    range = datetime.datetime.now(timezone.utc) - datetime.timedelta(hours=1)
    posts_list_1h = Post.objects.filter(datetime__gt=range)
    for post in posts_list_1h:
        response.append(
            {
                'datetime': post.datetime,
                'author': f"{post.user.first_name} {post.user.last_name}",
                'title': post.title,
                'content': post.content,                
                'hash' : post.hash,
                'txId' : post.txId
            }
        )
    return JsonResponse(response, safe=False)


def api_posts_str(request, str):
    posts_list = Post.objects.all()
    counter = 0
    for post in posts_list:
        if str in post.content:
            for word in post.content.split(" "):
                if word == str:
                    counter += 1
    return JsonResponse(counter, safe=False)
# ################### API tutti i post #######################
# def api_posts(request):
#     response = []
#     posts_lists = Post.objects.filter().order_by('datetime')
#     for post in posts_list:
#         response.append(
#             {
#                 'datetime': post.datetime,
#                 'author': f"{post.user.first_name} {post.user.last_name}",
#                 'title': post.title,
#                 'content': post.content,                
#                 'hash' : post.hash,
#                 'txId' : post.txId
#             }
#         )
#     return JsonResponse(response, safe=False)
#  ################### API tutti i post #######################

PROJECT_s2i/content/templates/content/partials/_carousel.html
{% load static %}
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <!-- <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="{% static 'content/images/first.svg' %}" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg> -->
        <img class="bd-placeholder-img" src="{% static 'content/images/1.png' %}" alt="My image" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Something special!</h1>
            <p>Create a post with interesting content.</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'content:posts' %}">Try now</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <!-- <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg> -->
        <img class="bd-placeholder-img" src="{% static 'content/images/2.png' %}" alt="My image" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">

        <div class="container">
          <div class="carousel-caption">
            <h1>PostOnChain!</h1>
            <p>Make it eternal with the power of blockchain.</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'content:info' %}">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <!-- <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg> -->
        <img class="bd-placeholder-img" src="{% static 'content/images/3.png' %}" alt="My image" width="100%" height="100%" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">


        <div class="container">
          <div class="carousel-caption text-end">
            <h1>Join us!</h1>
            <p>View and share posts from around the world.</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'accounts:signup' %}">Sign up</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

PROJECT_s2i/content/templates/content/partials/_central_content.html
<div class="container marketing">
  <h2 class="text-center"><strong>Last Posts</strong></h2>
  <br/>
  <br/>
    <!-- Three columns of text below the carousel -->
    <div class="row">

      {% for post in posts %}
      <div class="col-lg-4">
        <img class="bd-placeholder-img rounded-circle" src="static/content/images/avatar.svg" alt="My image" width="80" height="80">
    


        <h2>{{ post.title }}</h2>
        <p><i>{{ post.content|truncatewords:10 }}</i></p>
        <p><a class="btn btn-secondary" href="{% url 'content:post_detail' post.id %}">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->

      {% endfor %}

    <!-- START THE FEATURETTES

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider"> -->

    
    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

PROJECT_s2i/content/templates/content/partials/_footer.html
<br>
<footer class="text-center container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <!-- <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p> -->
  </footer>

PROJECT_s2i/content/templates/content/partials/_header.html
<header>
   <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
     <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'content:info' %}">PostOnChain</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       
       {% if user.is_authenticated and user.is_superuser %}
       
       <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav me-auto mb-2 mb-md-0">
           <li class="nav-item">
             <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
             <a class="nav-link" href="{% url 'content:home' %}">Home</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'content:APIs' %}">APIs</a>
           </li>
           <li class="nav-item">
             <!-- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
             <a class="nav-link" href="{% url 'content:posts' %}">Posts</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'content:posts_mng' %}">Management</a>
           </li>
         </ul>
           <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> -->
           <a style="margin-right: 5px" class="nav-link text-white" href="{% url 'accounts:profile' %}">{{ user.username }}</a>
           <a class="btn btn-outline-success" href="{% url 'accounts:logout' %}">Logout</a>
       </div>

       {% elif user.is_authenticated %}

       <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
            <a class="nav-link" href="{% url 'content:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'content:APIs' %}">APIs</a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
            <a class="nav-link" href="{% url 'content:posts' %}">Posts</a>
          </li>
        </ul>
          <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> -->
          <a style="margin-right: 5px" class="nav-link text-white" href="{% url 'accounts:profile' %}">{{ user.username }}</a>
          <a class="btn btn-outline-success" href="{% url 'accounts:logout' %}">Logout</a>
      </div>

        
      {% else %}

       <div class="collapse navbar-collapse" id="navbarCollapse">
         <ul class="navbar-nav me-auto mb-2 mb-md-0">
           <li class="nav-item">
            <a class="nav-link" href="{% url 'content:home' %}">Home</a>
           </li>
           <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">APIs</a>
           </li>
           <li class="nav-item">
             <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Posts</a>
           </li>
         </ul>
           <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> -->
           <a style="margin-right: 15px" class="btn btn-outline-success" href="{% url 'accounts:login' %}">Login</a>
           <a class="btn btn-outline-success" href="{% url 'accounts:signup' %}">Sign up</a>
       </div>

       {% endif %}

     </div>
   </nav>
 </header>