PROJECT_s2i/PROJECT_s2i/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PROJECT_s2i/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views 
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.sign_up, name='signup'),
]

PROJECT_s2i/content/urls.py
from django.urls import path
from . import views

app_name = "content"

urlpatterns = [
    path('', views.homepage, name='home'), # HOME
    path('info/', views.info, name='info'), # LEARN MORE 
    path('posts/', views.posts, name='posts'), # ELENCO E CREAZIONE POST 
    path('posts_mng/', views.posts_mng, name='posts_mng'), # GESTIONE POST 
    path('post/<int:id>/', views.post_detail, name='post_detail'), # DETTAGLIO POST 
    path('user/<int:id>/', views.user_id, name='user_id'), # USER E CORRISPONDENTE ID
    path('APIs/', views.APIs, name='APIs'), # ELENCO ENDPOINTS API
    path('api/1h/', views.api_posts_1h, name='api_posts_1h'), # ENDPOINT PER 1H 
    path('api/<str:str>/', views.api_posts_str, name='api_posts_str'), # ENDPOINT PER RICERCA DI UNA STRINGA 
]

PROJECT_s2i/accounts/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=CASCADE)
    birthday = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.user.username}'s profile"

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

PROJECT_s2i/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=120, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=120, required=False, help_text='Optional.')
    birthday = forms.DateField(required=False, help_text='Optional. (YYYY-MM-DD)')
    location = forms.CharField(max_length=120, help_text='Required.')
    email = forms.CharField(max_length=120, help_text='Required. Submit a valid email address')
    

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'birthday', 'location', 'password1', 'password2',)

PROJECT_s2i/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


def sign_up(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.birthday = form.cleaned_data.get('birthday')
            user.profile.location = form.cleaned_data.get('location')
            user.profile.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('accounts:profile')

    else:
        logout(request)
        form = RegistrationForm()
    
    return render(request, 'accounts/signup.html', {'form':form})

PROJECT_s2i/accounts/templates/accounts/profile.html
{% extends 'content/base.html' %}

{% block main %}
<main>

    <div class="container-fluid p-5 text-center">
        <!-- Aggiungere Icona Profilo -->
        <h5><strong>{{ user.username }}</strong></h5>
        <br />
        <ul>
            <li>Email: <strong>{{ user.email }}</strong></li>
            <li>Name: <strong>{{ user.first_name }}</strong></li>
            <li>Surname: <strong>{{ user.last_name }}</strong></li>
            <li>Birthday: <strong>{{ user.profile.birthday }}</strong></li>
            <li>Location: <strong>{{ user.profile.location }}</strong></li>
        </ul>
        <br />
        <a style="margin-right: 15px;" href="{% url 'accounts:logout' %}">Logout</a> <a href="{% url 'accounts:password_change' %}">Change password</a>
    </div>

</main>
{% endblock %}

PROJECT_s2i/accounts/templates/accounts/signup.html
{% extends 'content/base.html' %}

{% block main %}
<main>

    <div class="container-fluid p-5">

        <h2>Sign up</h2>
        <br>

    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
                <small style="color: grey;">{{ field.help_text }}</small>
            {% endif %}
        <p>
            {% for error in field.errors %}
                <small style="color: red;">{{ error }}</small>
            {% endfor %}
        </p>
        </p>
        {% endfor %}
        
        <input type="submit" value="Sign up">
    </form>

   </div>

    {% block footer %}
    {% include 'content/partials/_footer.html' %}
    {% endblock %}
    
</main>
{% endblock %}